### ISSUE TITLE
Request for Boundary Visualization Python Script

### ISSUE THREAD

**Issue by Pupillen** [wenxin-liu/neural_bounding#1]
Congratulations and admiration for the outstanding work presented at SIGGRAPH! Your contributions to the field are truly remarkable and inspiring.
I am particularly impressed by your recent paper and the innovative methodologies you have introduced. The depth of research and the clarity of presentation have provided immense value to the community.
I am currently working on a project that would greatly benefit from the boundary visualizations you demonstrated. I was wondering if it would be possible for you to share the Python script used for generating these boundary visualizations?
Having access to this script would significantly enhance my understanding and application of the techniques discussed in your paper.
Thank you for your time and consideration. I look forward to your positive response.

**Comment by wenxin-liu** [comment]
Discussed separately by email, and so closing this ticket.
